- src/_includes/components/header.css
- src/_includes/index.css
- src/_includes/partials/header.njk
- src/download.md
> fix: tweak buttons

- src/wiki/about-polymc.md
> (Draft) Add About PolyMC

- src/wiki/installing/slackware.md
it's the latest, develop revision of the launcher
> Add polymc-edge SBo link

- src/wiki/getting-started/download-mods.md
- src/wiki/getting-started/install-of-alternatives.md
- src/wiki/getting-started/installing-optifine.md
This makes some formatting more consistent, fix some types and add some explanations as to why you should use Optifine alternatives.
> Rework some things in the Wiki related to Optifine and alternatives

- .eleventy.js
- src/_includes/components/header.css
- src/_includes/partials/header.njk
- src/download.md
- src/index.md
- src/news.njk
Some settings still need tuning to get to the same file size as the original forest.webp, but otherwise this works pretty good.
> Use 11ty image instead of CSS background-image for hero

- src/wiki/development/build-instructions.md
https://polymc.org/wiki/development/build-instructions/#linux
smol pr, would you prefer just an issue about this?
> Fix not working linux (linux and freebsd) link in the build instructions

- src/wiki/getting-started/install-of-alternatives.md
Reccomends people optifine on forge
> of alternatives on forge

- src/wiki/faq/why.md
I'm quite new to the GitHub so I hope I did this right.
Just give some feedback and I can change whatever, I have much free time tomorrow.
love Bafmaster
> just some initial ideas for the fork page

- src/wiki/installing/linux/steam-deck.md
Added information in steam deck page on how to use CLI options in steam.
> add info about cli in steam deck page

- src/wiki/installing/linux/steam-deck.md
Added a guide to the Steam Deck Install page on how to set custom artwork for your PolyMC Non-Steam Game so that it looks better in the Steam Deck UI
> Added Steam Deck Artwork guide

- src/wiki/development/build-instructions.md
> Clarify Windows build dependencies

- src/wiki/getting-started/installing-java.md
Just like intel hd2000/hd3000 wiki, ispired from multimc wiki and links to a Java available on files.multimc.org
> add older Minecraft on macos wiki  

- src/wiki/getting-started/command-line-interface.md
change "righ-click" to "right-click"
> spelling error

- src/wiki/Java-settings.md
> fix an oopsie

- src/wiki/help-pages.md
- src/wiki/help-pages/APIs.md
- src/wiki/help-pages/Java-settings.md
- src/wiki/help-pages/Loader-mods.md
complementary to [PolyMC#430](https://github.com/PolyMC/PolyMC/pull/430)
> move help pages to help-pages

- src/wiki/installing/windows.md
Adds mention of the community maintained PortableApps.com installer to the page for installing on Windows
> Add PortableApps.com Installer

- src/wiki/getting-started/download-mods.md
> remove qsl from downloading mods wiki

- src/wiki/development/build-instructions.md
Added notes for building with separate meta repositories.
> added notes

- src/wiki/development/development-builds.md
> fix nightly.link link

- src/wiki/development/build-instructions.md
- docs: add IDE and Tooling section
- move CLion section
- fix: forgot a little thing
> Fix compile_commands in IDE section

- src/about.md
> update about page

- src/index.md
Modpack updating is not yet supported, so the current message is misleading.
> Correct the homepage message regarding modpack features

- src/news/moving-on.md
People are going to the wrong space :P
> update matrix link in moving on

- src/download/linux.md
- src/wiki/development/build-instructions.md
> Some fixes

- src/download/linux.md
Adds buttons that link to aur mpr git packages.
> Add buttons for git packages

- src/wiki/getting-started/installing-polymc.md
> change '.appimage' to '.AppImage'

- src/download/linux.md
- src/download/windows.md
- src/news/release-1.4.0.md
Needs to be updated with macOS signature once we actually release 1.4.0
> Add release 1.4.0 post

- src/index.md
Changes the Reddit link into a shield button.
> Change reddit link into shield button

- src/news/release-1.4.1.md
A very @flowln and @Scrumplex release :nerd_face:
> Add release 1.4.1 post

- src/wiki/development/development-builds.md
why not :)
this also makes them laid out horizontally, because it looks nicer
> Add gentoo-9999 to dev builds

- src/wiki/getting-started/installing-optifine.md
> Add standalone/jarmod instructions to the Installing Optifine page

- src/wiki/development/build-instructions.md
One package needed to be -dev and was not
> fix package name for QT6

- src/index.md
> Remove locked matrix channels
